Repository FRONTENDSCHOOL10/we-are-final-family, pull requests merged in 2024-09, with the labels that each got.

#39 Feature 컴포넌트 타임 셀렉터 마크업 스타일링 기능구현
  src/components/TimeSelector/TimeSelector.jsx
  src/components/TimeSelector/TimeSelector.module.css
  src/styles/media.css
Labels: 🌟 Feature

#42 Feature 컴포넌트 로케이션 마크업 스타일링 기능구현 #40
  src/components/LocationInput/CurrentLocationButton/CurrentLocationButton.jsx
  src/components/LocationInput/CurrentLocationButton/CurrentLocationButton.module.css
  src/components/LocationInput/LocationInput.jsx
  src/components/LocationInput/LocationInput.module.css
Labels: 🌟 Feature

#43 Refactor 헤더 리팩토링
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
  src/components/Header/HeaderBoard.jsx
  src/components/Header/HeaderBoard.module.css
  src/components/Header/HeaderChatDetail.jsx
  src/components/Header/HeaderChatDetail.module.css
  src/components/Header/HeaderDetail.jsx
  src/components/Header/HeaderDetail.module.css
  src/components/Header/HeaderHome.jsx
  src/components/Header/HeaderSearch.jsx
  src/components/Header/HeaderSearch.module.css
  src/components/Header/HeaderTitle.jsx
  src/components/Header/HeaderTitle.module.css
  src/components/Header/HeaderWrite.jsx
  src/components/Header/HeaderWrite.module.css
Labels: 🚧 Refactor

#45 feat: 프로필 카드 컴포넌트 및 하위컴포넌트 제작
  src/components/ChatProfileCard/ChatProfileCard.jsx
  src/components/ChatProfileCard/ChatProfileCard.module.css
  src/components/ProfileImg/Profile.module.css
  src/components/ProfileImg/ProfileImg.jsx
  src/components/ProfileImg/ProfileImg.module.css
  src/components/ProfileTitle/ProfileTitle.jsx
  src/components/ProfileTitle/ProfileTitle.module.css
Labels: 🌟 Feature

#47 Feature 작성페이지 라벨 컴포넌트
  src/components/CreateLabel/CreateLabel.jsx
  src/components/CreateLabel/CreateLabel.module.css
  src/components/DateSelector/DateSelector.jsx
  src/components/DateSelector/DateSelector.module.css
  src/components/PersonnelCounter/PersonnelCounter.jsx
  src/components/PersonnelCounter/PersonnelCounter.module.css
  src/components/navigation/Data/navigationData.js
  src/components/navigation/Navigation.jsx
Labels: 🌟 Feature

#49 Feature 성별선택 컴포넌트
  src/components/GenderSelector/GenderDisplay.jsx
  src/components/GenderSelector/GenderSelector.jsx
  src/components/GenderSelector/GenderSelectorButtons.jsx
  src/components/GenderSelector/GenderSelectorButtons.module.css
  src/components/GenderSelector/data/GenderSelectorData.js
  src/components/LocationInput/CurrentLocationButton/CurrentLocationButton.jsx
Labels: 🌟 Feature

#52 Refactor: 버튼 컴포넌트 폰트 스타일링 수정
  src/components/Button/Button.jsx
  src/components/Button/Button.module.css
Labels: 🚧 Refactor

#53 Feature 옵션 팝업 컴포넌트 추가
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
  src/components/IconButton/IconButton.jsx
  src/components/OptionPopup/OptionPopup.jsx
  src/components/OptionPopup/OptionPopup.module.css
Labels: 🌟 Feature, 🚧 Refactor

#57 Feature 인트로 페이지 마크업 스타일링
  src/components/Logo/Logo.jsx
  src/pages/Intro/Intro.jsx
  src/pages/Intro/Intro.module.css
Labels: 🌟 Feature

#59 Feat/component category filter buttons/l
  src/components/CategoryFilterButtons/CategoryFilterButtons.jsx
  src/components/CategoryFilterButtons/CategoryFilterButtons.module.css
  src/components/CategoryFilterButtons/CategoryModal.jsx
  src/components/CategoryFilterButtons/CategoryModal.module.css
  src/components/CategoryFilterButtons/CategoryModalMenu.jsx
  src/components/CategoryFilterButtons/CategoryModalMenu.module.css
  src/components/CategoryFilterButtons/ToggleAllButton.jsx
  src/components/CategoryFilterButtons/ToggleAllButton.module.css
  src/components/CategoryFilterButtons/data/CategoryFilterButtonsData.js
  src/components/CategorySelect/CategorySelect.jsx
  src/components/CategorySelect/data/CategorySelectData.js
Labels: 🌟 Feature

#61 Feature 밸리데이션 인풋 컴포넌트
  package.json
  pnpm-lock.yaml
  src/components/IconPreV/IconPreV.jsx
  src/components/IconPreV/IconPreV.module.css
  src/components/ValidationInput/TextInput.jsx
  src/components/ValidationInput/TextInput.module.css
  src/components/ValidationInput/ValidationInput.jsx
  src/components/ValidationInput/ValidationInput.module.css
Labels: 🌟 Feature

#62 Feat PendingCompnent 제작
  src/components/AgreeButton/AgreeButton.jsx
  src/components/AgreeButton/AgreeButton.module.css
  src/components/PendingCard/PendingCard.jsx
  src/components/PendingCard/PendingCard.module.css
  src/components/PendingList/PendingList.module.css
  src/components/PendingList/PendingLsit.jsx
  src/components/ProfileImg/ProfileImg.module.css
  src/components/ProfileTitle/ProfileTitle.jsx
Labels: 🌟 Feature, 🚧 Refactor

#64 Feature 모달/플로팅 버튼 컴포넌트
  src/components/FloatingButton/FloatingButton.jsx
  src/components/FloatingButton/FloatingButton.module.css
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.module.css
Labels: 🌟 Feature

#67 Feat: 말풍선 컴포넌트 및 현재시간 컴포넌트 제작
  App.jsx
  src/components/ChatSpeechbubble/ChatSpeechbubble.jsx
  src/components/ChatSpeechbubble/ChatSpeechbubble.module.css
  src/components/TimeNow/TimeNow.jsx
  src/components/TimeNow/TimeNow.module.css
Labels: 🌟 Feature

#69 Refactor: 버튼 컴포넌트 스타일 수정
  src/components/Button/Button.jsx
  src/components/Button/Button.module.css
  src/components/Button/ButtonWrap.jsx
Labels: 🚧 Refactor

#71 Remove: App.jsx 충돌될 코드 삭제
  App.jsx
Labels: 🚧 Refactor

#72 API 배포 테스트
  App.jsx
  src/Test.jsx
  src/main.jsx
  src/pages/Intro/Intro.jsx
Labels: 📬 API

#75 API 배포 테스트
  App.jsx
Labels: 📬 API

#77 API 배포 테스트
  src/components/Navigation1/Navigation.jsx
  src/components/Navigation1/Navigation.module.css
  src/components/Navigation1/data/NavigationData1.js
Labels: 📬 API

#79 API 배포 테스트 오타수정
  src/components/Navigation/Navigation.jsx
  src/components/Navigation/Navigation.module.css
  src/components/Navigation/data/NavigationData.js
Labels: 📬 API

#80 Send message component
  package.json
  pnpm-lock.yaml
  src/components/SendMessage/Icone/SendButton.jsx
  src/components/SendMessage/Icone/SendButton.module.css
  src/components/SendMessage/Icone/SendEmoje.jsx
  src/components/SendMessage/Icone/SendEmoje.module.css
  src/components/SendMessage/Icone/SendImg.module.css
  src/components/SendMessage/Icone/SnedImg.jsx
  src/components/SendMessage/SendMessage.jsx
  src/components/SendMessage/SendMessage.module.css
Labels: 🌟 Feature

#81 Feature 리스트 아이템 컴포넌트
  src/components/Badge/Badge.jsx
  src/components/Badge/Badge.module.css
  src/components/List/List.jsx
  src/components/List/List.module.css
  src/components/ListItem/ListItem.jsx
  src/components/ListItem/ListItem.module.css
  src/services/supabase.jsx
Labels: 🌟 Feature

#83 Feature 파티모집 카테고리 컴포넌트 추가
  src/components/PartyCategory/PartyCategory.jsx
  src/components/PartyCategory/PartyCategory.module.css
Labels: 🌟 Feature

#85 Docs 이슈, PR 템플릿 수정
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📑 Docs

#88 Refactor: 버튼 컴포넌트 스타일 수정
  src/components/Button/Button.jsx
  src/components/Button/Button.module.css
Labels: 🚧 Refactor

#90 Refactor:component interest card button 수정
  src/components/InterestCard/InterestCard.jsx
  src/components/InterestCardButton/InterestCardButton.jsx
  src/components/InterestCardButton/InterestCardButton.module.css
Labels: 🚧 Refactor

#92 Refactor 모달 컴포넌트 리팩토링
  src/components/Modal/Modal.jsx
  src/components/Modal/data.js
Labels: 🚧 Refactor

#94 Remove : 합쳐진 컴포넌트 폴더 삭제
  src/components/AgreeButton/AgreeButton.jsx
  src/components/AgreeButton/AgreeButton.module.css
  src/components/JoinPartyCard/JoinPartyCard.jsx
  src/components/JoinPartyCard/JoinPartyCard.module.css
  src/components/JoinPartyList/JoinPartyList.jsx
  src/components/PendingCard/PendingCard.jsx
  src/components/PendingCard/PendingCard.module.css
  src/components/PendingList/PendingLsit.jsx
  src/components/UserCard/UserCard.jsx
  src/components/UserCard/UserCard.module.css
Labels: 🌟 Feature, 🚧 Refactor

#97 Remove: InterestCard 컴포넌트 수정
  src/components/InterestCard/InterestCard.jsx
  src/components/InterestCard/InterestCard.module.css
  src/components/InterestCardButton/InterestCardButton.jsx
  src/components/InterestCardButton/InterestCardButton.module.css
Labels: 🌟 Feature

#100 index.html 및 공통 스타일 수정
  index.html
  manifest.webmanifest
  public/favicon.ico
  public/favicon.png
  public/favicon.svg
  public/logo.svg
  public/logo_192.png
  public/logo_512.png
  src/App.jsx
  src/components/Logo/Logo.jsx
  src/main.jsx
  src/styles/variables.css
Labels: 🚧 Refactor

#101 Remove: 버튼레퍼 컴포넌트 삭제, icon 폴더 삭제
  src/assets/button/arrow/down.svg
  src/assets/button/arrow/left.svg
  src/assets/button/icon/board.svg
  src/assets/button/icon/calendar.svg
  src/assets/button/icon/chat.svg
  src/assets/button/icon/check.svg
  src/assets/button/icon/onboard.svg
  src/assets/button/icon/onchat.svg
  src/assets/button/icon/onprofile.svg
  src/assets/button/icon/onship.svg
  src/assets/button/icon/plus.svg
  src/assets/button/icon/profile.svg
  src/assets/button/icon/ship.svg
  src/components/Button/Button.jsx
  src/components/Button/Button.module.css
  src/components/Button/ButtonWrap.jsx
Labels: 🚧 Refactor

#103 Setting 라우터 버전 업데이트
  package.json
Labels: ⚙️ Setting

#105 Setting: 모션,포켓베이스 삭제
  package.json
  pnpm-lock.yaml
Labels: ⚙️ Setting

#107 Refactor 인트로 화면 및 리스트 관련 컴포넌트 보완
  src/components/Badge/Badge.jsx
  src/components/Badge/Badge.module.css
  src/components/List/List.jsx
  src/components/ListItem/ListItem.jsx
  src/components/ListItem/ListItem.module.css
  src/pages/Intro/Intro.jsx
  src/pages/Intro/Intro.module.css
  src/utils/formatDate.js
Labels: 🚧 Refactor

#110 Setting import 규칙 수정 및 리엑트 라우터를 사용한 초기설정
  eslint.config.js
  src/App.jsx
  src/main.jsx
Labels: ⚙️ Setting

#113 Refactor: 버튼 컴포넌트 to 속성 들어오면 LInk 태그로 변함
  src/components/Button/Button.jsx
Labels: 🚧 Refactor

#115 Refactor 컴포넌트 리팩토링
  src/components/Badge/Badge.jsx
  src/components/FloatingButton/FloatingButton.jsx
  src/components/Header/Header.jsx
  src/components/IconButton/IconButton.jsx
  src/components/List/List.jsx
  src/components/ListItem/ListItem.jsx
  src/components/Modal/Modal.jsx
  src/components/PartyCategory/PartyCategory.jsx
Labels: 🚧 Refactor

#117 Feat: 댓글리스트 컴포넌트
  eslint.config.js
  src/components/CommentsList/CommentsList.jsx
  src/components/CommentsList/CommentsList.module.css
  src/components/CommentsList/data.js
Labels: 🌟 Feature

#120 Feature 페이지 구성 및 기타 수정
  src/App.jsx
  src/api/supabase.jsx
  src/components/Button/Button.module.css
  src/components/InterestCard/InterestCard.jsx
  src/components/List/List.jsx
  src/components/SendMessage/SendMessage.jsx
  src/hooks/useSupabase.jsx
  src/layout/RootLayout.jsx
  src/layout/RootLayout.module.css
  src/main.jsx
  src/pages/Board/Board.jsx
  src/pages/Board/Board.module.css
  src/pages/Chat/Chat.jsx
  src/pages/Chat/Chat.module.css
  src/pages/Chat/ChatRoom.jsx
  src/pages/Chat/ChatRoom.module.css
  src/pages/Home/Home.jsx
  src/pages/Home/Home.module.css
  src/pages/Home/HomeDetail.jsx
  src/pages/Home/HomeDetail.module.css
  src/pages/Home/HomeWrite.jsx
  src/pages/Home/HomeWrite.module.css
  src/pages/Intro/Intro.jsx
  src/pages/Intro/Intro.module.css
  src/pages/Login/Login.jsx
  src/pages/Login/Login.module.css
  src/pages/Profile/Profile.jsx
  src/pages/Profile/Profile.module.css
  src/pages/Profile/ProfileEdit.jsx
  src/pages/Profile/ProfileView.jsx
  src/pages/Register/Interest.jsx
  src/pages/Register/Interest.module.css
  src/pages/Register/Register.jsx
  src/pages/Register/Register.module.css
  src/pages/Search/Search.jsx
  src/pages/index.js
  src/router.jsx
Labels: 🌟 Feature, 🚧 Refactor

#122 Modify 컴포넌트 마크업/스타일 수정
  src/components/Button/Button.module.css
  src/components/ChatProfileCard/ChatProfileCard.jsx
  src/components/ChatProfileCard/ChatProfileCard.module.css
  src/components/CommentsList/CommentsList.jsx
  src/components/CommentsList/CommentsList.module.css
  src/components/IconButton/IconButton.module.css
  src/components/InterestCard/InterestCard.jsx
  src/components/InterestCard/InterestCard.module.css
  src/components/JoinPartyList/JoinPartyList.jsx
  src/components/JoinPartyList/JoinPartyList.module.css
  src/components/ListFilterButtons/ListFilterButtons.jsx
  src/components/ListFilterButtons/ListFilterButtons.module.css
  src/components/ListFilterButtons/ListModal.jsx
  src/components/ListFilterButtons/ListModal.module.css
  src/components/ListFilterButtons/ToggleAllButton.jsx
  src/components/ListFilterButtons/ToggleAllButton.module.css
  src/components/ListFilterButtons/ToggleListMenu.jsx
  src/components/ListFilterButtons/ToggleListMenu.module.css
  src/components/Navigation/Navigation.jsx
  src/components/Navigation/Navigation.module.css
  src/components/PendingList/PendingList.module.css
  src/components/PendingList/PendingLsit.jsx
  src/components/ProfileTitle/ProfileTitle.jsx
  src/components/ProfileTitle/ProfileTitle.module.css
  src/components/UserCard/UserCard.jsx
  src/components/UserCard/UserCard.module.css
  src/components/ValidationInput/TextInput.module.css
  src/components/ValidationInput/ValidationInput.jsx
  src/components/ValidationInput/ValidationInput.module.css
  src/components/__ExampleForIconFonts/Exam.jsx
  src/components/__ExampleForIconFonts/Exam.module.css
  src/components/__IconPreV/IconPreV.jsx
  src/components/__IconPreV/IconPreV.module.css
Labels: 🚧 Refactor

#123 Feat: UserCard 컴포넌트 기능 추가
  src/components/ProfileImg/ProfileImg.jsx
  src/components/ProfileImg/ProfileImg.module.css
  src/components/UserCard/UserCard.jsx
  src/components/UserCard/UserCard.module.css
Labels: 🌟 Feature

#126 Feature 약관동의 컴포넌트
  .github/ISSUE_TEMPLATE.md
  src/components/SignUpList/AgreementForm.jsx
  src/components/SignUpList/AgreementForm.module.css
  src/components/SignUpList/CheckBoxList.jsx
  src/components/SignUpList/CheckboxList.module.css
  src/components/SignUpList/SignUpList.jsx
  src/components/Toggle/Toggle.jsx
  src/components/Toggle/Toggle.module.css
  src/components/ToggleButton/ToggleButton.jsx
Labels: 🌟 Feature

#128 Refactor 게시글 작성, 네비게이션 컴포넌트
  src/components/Navigation/Navigation.jsx
  src/components/Navigation/Navigation.module.css
  src/components/Navigation/data/NavigationData.js
  src/components/ValidationInput/TextInput.jsx
  src/components/ValidationInput/ValidationInput.jsx
  src/components/ValidationInput/ValidationInput.module.css
  src/components/WriteForm/ButtonSelector/ButtonSelector.jsx
  src/components/WriteForm/ButtonSelector/ButtonSelector.module.css
  src/components/WriteForm/ButtonSelector/Toggle/Toggle.jsx
  src/components/WriteForm/ButtonSelector/Toggle/Toggle.module.css
  src/components/WriteForm/ButtonSelector/data/GenderData.js
  src/components/WriteForm/DateSelector/DateSelector.module.css
  src/components/WriteForm/LocationButton/LocationButton.module.css
  src/components/WriteForm/PersonnelCounter/PersonnelCounter.module.css
  src/components/WriteForm/TimeSelector/TimeSelector.module.css
  src/components/WriteForm/WriteForm.jsx
  src/utils/validation.js
Labels: 🚧 Refactor

#131 Feature 관심분야 선택 페이지 렌더링 작업
  src/api/DataService.jsx
  src/components/InterestCardList/InterestCard.jsx
  src/components/InterestCardList/InterestCard.module.css
  src/components/InterestCardList/InterestCardList.jsx
  src/components/InterestCardList/InterestCardList.module.css
  src/components/InterestSelector/InterestSelector.jsx
  src/components/InterestSelector/InterestSelector.module.css
  src/components/supabase/UserForm.jsx
  src/components/supabase/UserList.jsx
  src/hooks/useSupabase.jsx
  src/pages/Register/Interest.jsx
Labels: 🌟 Feature

#133 Feat: StudyPost 컴포넌트
  src/components/StudyPost/StudyPost.jsx
  src/components/StudyPost/StudyPost.module.css
Labels: 🌟 Feature

#138 BugFix 네비게이션 바 아이콘색상 오류 개선
  src/components/App/Header.jsx
  src/components/App/Navigation.jsx
  src/components/PendingList/PendingList.jsx
  src/components/WriteForm/LocationButton/CurrentLocationButton/CurrentLocationButton.jsx
  src/components/WriteForm/LocationButton/CurrentLocationButton/CurrentLocationButton.module.css
  src/pages/Home/HomeDetail.jsx
Labels: 🐞 BugFix

#135 Api/page interest/l
  src/components/InterestCardList/InterestCard.jsx
  src/components/InterestCardList/InterestCard.module.css
  src/components/InterestCardList/InterestCardList.jsx
  src/components/InterestCardList/InterestCardList.module.css
  src/components/InterestSelector/InterestSelector.jsx
  src/components/InterestSelector/InterestSelector.module.css
  src/pages/Register/Interest.jsx
  src/stores/InterestStore.js
Labels: 📬 API

#140 Refactor,Feature 회원가입시 데이터 전송 훅함수 리팩토링 회원가입 로직 리팩토링 필수
  src/api/DataService.js
  src/api/DataService.jsx
  src/components/ValidationInput/TextInput.jsx
  src/components/ValidationInput/ValidationInput.jsx
  src/components/ValidationInput/useRegisterStore.js
  src/pages/Register/Register.jsx
Labels: 🌟 Feature, 🚧 Refactor

#143 Refactor: Data Api 함수 만듬
  src/api/DataService.js
Labels: 🚧 Refactor

#146 Feature: Helmet(meta), Suspense, Error, Fallback 추가
  src/components/FloatingButton/FloatingButton.module.css
  src/layout/RootLayout.jsx
  src/pages/Board/BoardDetail.jsx
  src/pages/Board/BoardDetail.module.css
  src/pages/Board/BoardWrite.jsx
  src/pages/Board/BoardWrite.module.css
  src/pages/Error.jsx
  src/pages/Error.module.css
  src/pages/Fallback.jsx
  src/pages/index.js
  src/router.jsx
Labels: 🌟 Feature

#149 로그인 페이지 api 기반 기능구현 관심분야 페이지 선택 제한 기능 추가 TextInput 삭제 후 밸리데이션 인풋으로 합침
  src/components/ListFilterButtons/ListFilterButtons.jsx
  src/components/ValidationInput/TextInput.jsx
  src/components/ValidationInput/TextInput.module.css
  src/components/ValidationInput/ValidationInput.jsx
  src/components/ValidationInput/ValidationInput.module.css
  src/pages/Login/Login.jsx
  src/pages/Register/Interest.jsx
  src/stores/InterestStore.js
  src/utils/auth.js
Labels: 🌟 Feature, 📬 API

#150 Refactor : 회원가입 페이지 리펙토링
  package.json
  pnpm-lock.yaml
  src/components/Modal/Modal.jsx
  src/components/SendMessage/SendMessage.jsx
  src/components/ValidationInput/ValidationInput.jsx
  src/components/ValidationInput/ValidationInput.module.css
  src/pages/Login/Login.jsx
  src/pages/Register/Register.jsx
  src/stores/useRegisterStore.js
Labels: 🌟 Feature

#152 Feature Header/IconButton 수정
  src/components/App/Header.jsx
  src/components/App/Header.module.css
  src/components/IconButton/IconButton.jsx
  src/components/OptionPopup/OptionPopup.module.css
  src/pages/Board/Board.jsx
  src/pages/Board/BoardDetail.jsx
  src/pages/Board/BoardWrite.jsx
  src/pages/Chat/Chat.jsx
  src/pages/Chat/ChatRoom.jsx
  src/pages/Error.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/HomeDetail.jsx
  src/pages/Home/HomeWrite.jsx
  src/pages/Search/Search.jsx
Labels: 🌟 Feature

#155 Feat:회원가입시 로컬스토리지에 있는 관심분야 데이터 수파베이스에 전달
  src/pages/Register/Interest.jsx
  src/pages/Register/Register.jsx
Labels: 🌟 Feature, 🚧 Refactor

#156 Feat/chating/g
  src/components/ChatSpeechbubble/ChatSpeechbubble.jsx
  src/components/ChatSpeechbubble/ChatSpeechbubble.module.css
  src/pages/Chat/ChatRoom.jsx
Labels: 🚧 Refactor

#158 Feature : 파티모집 페이지 리스트 렌더링
  src/components/App/Header.jsx
  src/components/Button/Button.module.css
  src/components/FloatingButton/FloatingButton.jsx
  src/components/List/FillterButton.module.css
  src/components/List/FilterButton.jsx
  src/components/List/FilterModal.jsx
  src/components/List/FilterModal.module.css
  src/components/List/List.jsx
  src/components/List/ListItem.jsx
  src/components/List/ListItem.module.css
  src/components/List/PartyCategory.jsx
  src/components/List/PartyCategory.module.css
  src/components/ListItem/ListItem.jsx
  src/pages/Board/Board.jsx
  src/pages/Board/Board.module.css
  src/pages/Home/Home.jsx
  src/pages/Home/Home.module.css
  src/utils/formatDate.js
Labels: 🌟 Feature

#161 Feat chatting 리스트 페이지 들어오면 데이터가 변경되었을시, 자동으로 패칭
  src/components/ChatProfileCard/ChatProfileCard.jsx
  src/components/ChatSpeechbubble/ChatSpeechbubble.jsx
  src/components/ChatSpeechbubble/ChatSpeechbubble.module.css
  src/components/SendMessage/SendMessage.jsx
  src/components/TimeNow/TimeNow.jsx
  src/components/TimeNow/TimeNow.module.css
  src/pages/Chat/Chat.jsx
  src/pages/Chat/ChatRoom.jsx
  src/stores/chatStore.js
  src/stores/currentUser.js
  src/utils/formatDate.js
Labels: 🌟 Feature

#163 Feature 검색 기능 구현
  src/components/ListFilterButtons/ListFilterButtons.jsx
  src/components/ListFilterButtons/data/ListFilterButtonsData.js
  src/components/ListSearch/ListSearch.jsx
  src/components/ListSearch/ListSearch.module.css
  src/pages/Search/Search.jsx
  src/pages/Search/Search.module.css
  src/pages/Search/SearchBoard.jsx
  src/pages/index.js
  src/router.jsx
Labels: 🌟 Feature, 📬 API

#165 Feature 검색 기능 추가
  src/components/App/Header.jsx
Labels: 🌟 Feature

#167 Fix: 동일한 임포트 삭제
  src/pages/Chat/ChatRoom.jsx
Labels: 🐞 BugFix

#169 feat 로그인페이지 엔터기능 추가
  src/components/ValidationInput/ValidationInput.jsx
  src/pages/Login/Login.jsx
Labels: 🐞 BugFix

#171 BugFix 검색 에러 수정
  src/pages/Search/Search.jsx
Labels: 🐞 BugFix

#173 Feature 게시글 댓글
  src/components/CommentsList/Comment.jsx
  src/components/CommentsList/Comment.module.css
  src/components/CommentsList/CommentsList.jsx
  src/components/CommentsList/CommentsList.module.css
  src/pages/Board/BoardDetail.jsx
Labels: 🌟 Feature, 📬 API

#176 Feature : 파티모집 글 작성 화면
  src/components/ListSelect/ListSelect.jsx
  src/components/ListSelect/ListSelect.module.css
  src/components/WriteForm/DateSelector/Calender/Calender.jsx
  src/components/WriteForm/DateSelector/Calender/Calender.module.css
  src/components/WriteForm/DateSelector/DateSelector.module.css
  src/components/WriteForm/LocationButton/LocationButton.module.css
  src/components/WriteForm/PeopleCounter/PeopleCounter.jsx
  src/components/WriteForm/PeopleCounter/PeopleCounter.module.css
  src/components/WriteForm/PersonnelCounter/PersonnelCounter.module.css
  src/components/WriteForm/TimeSelector/TimeSelector.jsx
  src/components/WriteForm/TimeSelector/TimeSelector.module.css
  src/pages/Home/HomeWrite.jsx
  src/pages/Home/HomeWrite.module.css
Labels: 🌟 Feature

#178 Refactor/chatting/g
  src/components/ChatSpeechbubble/ChatSpeechbubble.jsx
  src/components/IconButton/IconButton.jsx
  src/components/SendMessage/SendMessage.jsx
  src/pages/Chat/Chat.jsx
  src/pages/Chat/ChatRoom.jsx
  src/pages/Login/Login.jsx
  src/stores/chatStore.js
  src/utils/debounce.js
Labels: 🌟 Feature, 🚧 Refactor

#183 Feature 관심분야 페이지 업데이트
  src/components/SignUpList/AgreementForm.jsx
  src/components/SignUpList/CheckBoxList.jsx
  src/components/WriteForm/PersonnelCounter/PersonnelCounter.jsx
  src/components/WriteForm/TimeSelector/TimeSelector.jsx
  src/components/WriteForm/WriteForm.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Register/Register.jsx
  src/utils/clearLocalStorage.js
Labels: 🌟 Feature, 📬 API

#185 Refactor 오타 수정
  src/components/SignUpList/CheckBoxList.module.css
Labels: 🚧 Refactor

#186 feat: react-virtualized 설치후 뷰포인트 에 들어온 데이터만 불러오기, 무한스크롤
  package.json
  pnpm-lock.yaml
  src/components/SendMessage/SendMessage.jsx
  src/components/UserCard/UserCard.jsx
  src/pages/Chat/Chat.jsx
  src/pages/Chat/ChatRoom.jsx
  src/pages/Chat/chatTest.jsx
  src/stores/chatStore.js
  vite.config.js
Labels: 🌟 Feature, 🚧 Refactor

#189 fix: userCard 경로수정 restprops 추가
  src/components/JoinPartyList/JoinPartyList.jsx
  src/components/PendingList/PendingList.jsx
  src/components/UserCard/UserCard.jsx
Labels: 🐞 BugFix

#190 refactor 빌드 오류 수정
  src/components/SignUpList/CheckBoxList.module.css
  src/components/WriteForm/WriteForm.jsx
Labels: 🚧 Refactor, ✅ Test

#192 Refactor 오타 수정 및 빌드오류
  src/components/SignUpList/AgreementForm.jsx
  src/components/SignUpList/CheckboxList.jsx
  src/components/SignUpList/CheckboxList.module.css
Labels: 🚧 Refactor, ✅ Test

#193 Feat : 리스트 렌더링
  public/manifest.webmanifest
  src/components/App/Header.jsx
  src/components/List/FilterButton.jsx
  src/components/List/FilterButton.module.css
  src/components/List/FilterModal.jsx
  src/components/List/FilterModal.module.css
  src/components/List/List.jsx
  src/components/List/ListItem.jsx
  src/pages/Home/Home.jsx
  src/pages/NoneData.jsx
  src/stores/useHomeStore.js
Labels: 🌟 Feature, 🚧 Refactor

#198 Refactor RootLayout 수정
  src/components/InterestCardList/InterestCardList.jsx
  src/layout/RootLayout.jsx
  src/pages/Intro/Intro.jsx
Labels: 🚧 Refactor

#199 Style : 컴포넌트 및 페이지 스타일 보완
  src/assets/fonts/icomoon.eot
  src/assets/fonts/icomoon.svg
  src/assets/fonts/icomoon.ttf
  src/assets/fonts/icomoon.woff
  src/components/App/Header.module.css
  src/components/App/Navigation.module.css
  src/components/InterestCardList/InterestCardList.module.css
  src/components/List/FilterButton.module.css
  src/components/List/FilterModal.module.css
  src/components/List/List.jsx
  src/components/List/ListItem.module.css
  src/components/List/PartyCategory.module.css
  src/components/ListFilterButtons/ListFilterButtons.module.css
  src/components/ListSearch/ListSearch.jsx
  src/components/ValidationInput/ValidationInput.jsx
  src/components/ValidationInput/ValidationInput.module.css
  src/pages/Fallback.jsx
  src/pages/NoneData.jsx
  src/pages/Search/Search.jsx
  src/pages/Search/Search.module.css
  src/styles/iconfonts.css
Labels: 🚧 Refactor

#201 Feat 리스트-디테일 페이지 렌더링
  src/components/Badge/Badge.jsx
  src/components/List/List.jsx
  src/pages/Home/HomeDetail.jsx
  src/pages/Home/HomeDetail.module.css
  src/stores/useListStore.js
  src/utils/formatDate.js
Labels: 🌟 Feature

#203 Feat 게시판 리스트-디테일 페이지 렌더링
  src/components/CommentsList/Comment.jsx
  src/components/CommentsList/Comment.module.css
  src/components/CommentsList/CommentsList.module.css
  src/components/List/List.jsx
  src/components/List/ListItem.jsx
  src/components/SendMessage/SendMessage.jsx
  src/components/SendMessage/SendMessage.module.css
  src/pages/Board/Board.jsx
  src/pages/Board/BoardDetail.jsx
  src/pages/Board/BoardDetail.module.css
  src/pages/Chat/ChatRoom.module.css
Labels: 🌟 Feature

#205 BugFix 페이지 이동 시 파티모집 페이지 오류
  src/components/List/List.jsx
  src/pages/NoneData.jsx
Labels: 🐞 BugFix

#207 Feature 파티모집 게시글 작성 페이지
  src/components/ListSelect/ListSelect.jsx
  src/components/WriteForm/DateSelector/Calender/Calender.jsx
  src/components/WriteForm/DateSelector/DateSelector.jsx
  src/components/WriteForm/LocationButton/CurrentLocationButton/CurrentLocationButton.jsx
  src/components/WriteForm/LocationButton/LocationButton.jsx
  src/components/WriteForm/PersonnelCounter/PersonnelCounter.jsx
  src/components/WriteForm/TimeSelector/TimeSelector.jsx
  src/pages/Home/HomeWrite.jsx
  src/pages/Home/HomeWriteNext.jsx
  src/pages/Home/HomeWriteNext.module.css
  src/pages/index.js
  src/router.jsx
  src/stores/dateUtils.js
  src/stores/homeWriteStore.js
  src/utils/fetchListData.js
  src/utils/formatDate.js
Labels: 🌟 Feature, 📬 API

#209 Refactor Profile 페이지 및 기타 스타일 수정
  src/components/ProfileImg/ProfileImg.jsx
  src/components/ProfileImg/ProfileImg.module.css
  src/components/ProfileList/ProfileList.jsx
  src/components/SignUpList/AgreementForm.jsx
  src/components/SignUpList/AgreementForm.module.css
  src/components/SignUpList/CheckboxList.jsx
  src/components/SignUpList/CheckboxList.module.css
  src/components/SignUpList/SignUpList.jsx
  src/components/WriteForm/ButtonSelector/ButtonSelector.jsx
  src/components/WriteForm/ButtonSelector/ButtonSelector.module.css
  src/components/WriteForm/ButtonSelector/Toggle/Toggle.jsx
  src/components/WriteForm/ButtonSelector/Toggle/Toggle.module.css
  src/pages/Profile/Profile.jsx
  src/pages/Profile/Profile.module.css
  src/pages/Profile/ProfileEdit.jsx
  src/pages/Profile/ProfileView.jsx
Labels: 🚧 Refactor

#210 Feat/agree user/g
  src/components/JoinPartyList/JoinPartyList.jsx
  src/components/PendingList/PendingList.jsx
  src/components/UserCard/UserCard.jsx
  src/pages/Home/HomeDetail.jsx
  src/stores/useListStore.js
  src/stores/usePartyStore.js
Labels: 🌟 Feature

#213 Style 파티모집 게시글 작성 화면 스타일링
  src/components/WriteForm/ButtonSelector/ButtonSelector.jsx
  src/components/WriteForm/ButtonSelector/ButtonSelector.module.css
  src/components/WriteForm/ButtonSelector/Toggle/Toggle.jsx
  src/pages/Home/HomeWriteNext.jsx
  src/pages/Home/HomeWriteNext.module.css
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileEdit.jsx
  src/router.jsx
  src/styles/variables.css
Labels: 🐞 BugFix, 🚧 Refactor

#214 feature 게시판 작성글 페이지
  src/components/ListSelect/ListSelect.jsx
  src/components/LogoAnimation/LogoAnimation.jsx
  src/components/LogoAnimation/LogoAnimation.module.css
  src/pages/Board/Board.jsx
  src/pages/Board/BoardWrite.jsx
  src/pages/Board/BoardWrite.module.css
  src/pages/Fallback.jsx
  src/stores/InterestStore.js
  src/utils/fetchListData.js
Labels: 🌟 Feature, 📬 API

#217 Feature 게시글 이미지 렌더링
  src/Test.jsx
  src/components/List/List.jsx
  src/components/List/ListItem.jsx
  src/components/ListSearch/ListSearch.jsx
  src/components/ListSearch/ListSearch.module.css
  src/components/SendMessage/SendMessage.jsx
  src/pages/Board/BoardDetail.jsx
  src/pages/Board/BoardDetail.module.css
  src/pages/Board/BoardWrite.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/Login.module.css
  src/stores/useCommentCountStore.js
  src/stores/useViewCountStore.js
  src/utils/useViewCount.js
Labels: 🌟 Feature, 📬 API

#218 Fix: 채팅 구독안되는 버그 랜더링 안되는버그 수정 참여중 대기중 언마운트되도 계속 랜더링 되는 버그 수정
  src/components/ChatProfileCard/ChatProfileCard.jsx
  src/components/JoinPartyList/JoinPartyList.jsx
  src/components/PendingList/PendingList.jsx
  src/pages/Chat/Chat.jsx
  src/pages/Chat/ChatRoom.jsx
  src/pages/Home/HomeDetail.jsx
  src/router.jsx
  src/stores/chatStore.js
Labels: 🐞 BugFix, 🌟 Feature

#221 Feature 파티모집 작성페이지
  src/components/WriteForm/LocationButton/CurrentLocationButton/CurrentLocationButton.jsx
  src/pages/Board/BoardWrite.jsx
  src/pages/Board/BoardWrite.module.css
  src/pages/Home/HomeWrite.jsx
  src/pages/Home/HomeWrite.module.css
  src/pages/Home/HomeWriteNext.jsx
  src/pages/Login/Login.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Register/Interest.jsx
  src/router.jsx
  src/stores/homeWriteStore.js
  src/stores/useUserRecordsCount.js
Labels: 🌟 Feature, 📬 API

#223 Refactor 프로필 페이지 경로 이슈
  src/pages/Profile/Profile.jsx
Labels: 🚧 Refactor

#225 Feature 게시판페이지 무한스크롤
  src/components/List/List.jsx
  src/components/List/ListItem.jsx
  src/components/SendMessage/SendMessage.jsx
  src/pages/Chat/ChatRoom.jsx
  src/stores/chatStore.js
  src/stores/useCommentCountStore.js
  src/stores/useListStore.js
  src/utils/useViewCount.js
  vercel.json
Labels: 🌟 Feature, 🚧 Refactor, 🌏 Deploy

#227 Refactor 빈채팅방 만들기 채팅내역 사용자이름 랜더링 및 버그수정
  src/components/JoinPartyList/JoinPartyList.jsx
  src/components/PendingList/PendingList.jsx
  src/components/ProfileTitle/ProfileTitle.jsx
  src/components/UserCard/UserCard.jsx
  src/components/UserCard/UserCard.module.css
  src/pages/Chat/ChatRoom.jsx
  src/pages/Chat/ChatSendMessages.jsx
  src/pages/Chat/ChatsendMessages.module.css
  src/pages/Home/HomeDetail.jsx
  src/stores/chatStore.js
Labels: 🚧 Refactor

#228 Feature 파티지원기능 구현
  src/App.jsx
  src/Test.jsx
  src/components/JoinPartyList/JoinPartyList.jsx
  src/components/Logo/Logo.jsx
  src/components/PendingList/PendingList.jsx
  src/components/ProfileList/ProfileList.jsx
  src/components/UserCard/UserCard.jsx
  src/pages/Home/HomeDetail.jsx
  src/pages/Home/HomeWriteNext.jsx
  src/pages/Intro/Intro.jsx
  src/pages/Intro/Intro.module.css
  src/pages/Profile/Profile.jsx
  src/pages/Profile/Profile.module.css
  src/stores/useThemeStore.js
  src/styles/variables.css
Labels: 🌟 Feature

#229 Fix 구독기능 버그수정 충동사항 수정
  src/components/PendingList/PendingList.jsx
  src/components/UserCard/UserCard.jsx
  src/pages/Chat/ChatRoom.jsx
  src/pages/Chat/ChatSendMessages.jsx
  src/stores/chatStore.js
Labels: 🐞 BugFix

#232 feat joinList 카드 클릭하면채팅연결
  src/components/UserCard/UserCard.jsx
Labels: 🌟 Feature

#233 Bugfix 리스트 오류 수정
  src/pages/Profile/Profile.jsx
  src/stores/useListStore.js
  src/stores/useViewCountStore.js
Labels: 🌟 Feature

#235 Feature 파티모집 인원 수 렌더링
  src/components/List/List.jsx
  src/stores/useListStore.js
Labels: 🌟 Feature

#238 bugfix lint 수정
  src/components/InterestSelector/InterestSelector.jsx
  src/components/ListFilterButtons/ListModal.jsx
  src/components/SendMessage/Icone/SendEmoji.jsx
  src/components/WriteForm/LocationButton/CurrentLocationButton/CurrentLocationButton.jsx
  src/components/WriteForm/TimeSelector/TimeSelector.jsx
  src/pages/Chat/ChatRoom.jsx
  src/pages/Register/Interest.jsx
Labels: 🐞 BugFix

#240 feature 파티디테일 이미지 추가
  src/pages/Home/HomeDetail.jsx
  src/pages/Home/HomeDetail.module.css
Labels: 🌟 Feature

#242 BugFix 채팅 오류 수정 및 기본프로필이미지 #241
  public/bonobobono.webp
  src/Test.jsx
  src/assets/testImg/bonobobono.jpeg
  src/components/ProfileImg/ProfileImg.jsx
  src/components/SendMessage/Icone/SendEmoji.jsx
  src/pages/Chat/ChatRoom.jsx
  src/pages/Home/HomeDetail.jsx
  src/router.jsx
Labels: 🐞 BugFix

#243 Style 다크 모드 추가
  src/App.jsx
  src/components/App/Header.module.css
  src/components/App/Navigation.module.css
  src/components/Button/Button.module.css
  src/components/ChatProfileCard/ChatProfileCard.module.css
  src/components/ChatSpeechbubble/ChatSpeechbubble.jsx
  src/components/ChatSpeechbubble/ChatSpeechbubble.module.css
  src/components/CommentsList/Comment.module.css
  src/components/CommentsList/CommentsList.module.css
  src/components/FloatingButton/FloatingButton.module.css
  src/components/IconButton/IconButton.module.css
  src/components/InterestCardList/InterestCard.module.css
  src/components/InterestSelector/InterestSelector.module.css
  src/components/JoinPartyList/JoinPartyList.module.css
  src/components/List/FilterButton.module.css
  src/components/List/ListItem.module.css
  src/components/List/PartyCategory.module.css
  src/components/ListFilterButtons/ListFilterButtons.module.css
  src/components/ListSearch/ListSearch.module.css
  src/components/ListSelect/ListSelect.jsx
  src/components/ListSelect/ListSelect.module.css
  src/components/Modal/Modal.module.css
  src/components/OptionPopup/OptionPopup.module.css
  src/components/PendingList/PendingList.module.css
  src/components/ProfileTitle/ProfileTitle.module.css
  src/components/SendMessage/Icone/SendEmoji.module.css
  src/components/SendMessage/Icone/SendImg.module.css
  src/components/SendMessage/SendMessage.module.css
  src/components/SignUpList/AgreementForm.module.css
  src/components/SignUpList/CheckboxList.module.css
  src/components/UserCard/UserCard.module.css
  src/components/ValidationInput/ValidationInput.module.css
  src/components/WriteForm/ButtonSelector/ButtonSelector.module.css
  src/components/WriteForm/ButtonSelector/Toggle/Toggle.module.css
  src/components/WriteForm/DateSelector/Calender/Calender.module.css
  src/components/WriteForm/DateSelector/DateSelector.module.css
  src/components/WriteForm/LocationButton/CurrentLocationButton/CurrentLocationButton.module.css
  src/components/WriteForm/LocationButton/LocationButton.module.css
  src/components/WriteForm/PersonnelCounter/PersonnelCounter.module.css
  src/components/WriteForm/TimeSelector/TimeSelector.module.css
  src/layout/RootLayout.module.css
  src/pages/Board/BoardDetail.module.css
  src/pages/Board/BoardWrite.module.css
  src/pages/Chat/Chat.module.css
  src/pages/Chat/ChatsendMessages.module.css
  src/pages/Home/Home.module.css
  src/pages/Home/HomeDetail.module.css
  src/pages/Home/HomeWrite.module.css
  src/pages/Home/HomeWriteNext.module.css
  src/pages/Intro/Intro.module.css
  src/pages/Profile/Profile.jsx
  src/pages/Profile/Profile.module.css
  src/pages/Register/Interest.module.css
  src/pages/Register/Register.module.css
  src/pages/Search/Search.module.css
  src/stores/useThemeStore.js
  src/styles/variables.css
Labels: 🚧 Refactor

#246 Style 다크 모드 추가
  src/components/Button/Button.module.css
  src/components/InterestSelector/InterestSelector.module.css
  src/components/List/FilterModal.module.css
  src/components/LogoAnimation/LogoAnimation.jsx
  src/components/LogoAnimation/LogoAnimation.module.css
  src/components/ProfileImg/ProfileImg.module.css
  src/layout/RootLayout.module.css
  src/pages/Board/Board.module.css
  src/pages/Board/BoardWrite.module.css
  src/pages/Chat/Chat.module.css
  src/pages/Fallback.jsx
  src/pages/Home/HomeWrite.module.css
  src/pages/Intro/Intro.jsx
  src/pages/Intro/Intro.module.css
  src/styles/variables.css
Labels: 🚧 Refactor

#247 Refactor 페이지 컴포넌트 리팩토링
  src/components/App/Header.jsx
  src/components/JoinPartyList/JoinPartyList.jsx
  src/components/List/List.jsx
  src/components/ListFilterButtons/ListModal.jsx
  src/components/ListSelect/data/CategorySelectData.js
  src/components/ListSelect/data/TitleSelectData.js
  src/components/PendingList/PendingList.jsx
  src/components/SendMessage/SendMessage.jsx
  src/components/UserCard/UserCard.jsx
  src/pages/Board/BoardDetail.jsx
  src/pages/Board/BoardWrite.jsx
  src/pages/Board/BoardWrite.module.css
  src/pages/Chat/Chat.jsx
  src/pages/Chat/ChatSendMessages.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/HomeWriteNext.jsx
  src/pages/Login/Login.jsx
  src/pages/Register/Register.jsx
  src/stores/chatStore.js
  src/stores/usePartyStore.js
Labels: 🚧 Refactor

#249 ReadMe 파일 수정
  README.md
Labels: 📑 Docs

#250 Update README.md
  README.md
Labels: 📑 Docs

#253 Docs : 리드미 수정
  README.md
Labels: 📑 Docs

#255 feature 모바일 환경 개선
  src/App.jsx
  src/styles/variables.css
  src/utils/viewport.JS
Labels: 🌟 Feature

#258 BugFix 모바일 환경 개선
  src/App.jsx
  src/utils/viewport.JS
Labels: 🐞 BugFix

#261 bugfix 원복
  src/App.jsx
  src/styles/variables.css
  src/utils/viewport.JS
Labels: 🐞 BugFix

#263 Update README.md
  README.md
Labels: 📑 Docs

#265 Fix : eslint 경고수정
  src/pages/Board/BoardDetail.jsx
  src/pages/Board/BoardWrite.jsx
Labels: 🐞 BugFix

#267 BugFix 검색 기능 이슈 해결
  src/components/ListFilterButtons/ToggleAllButton.jsx
  src/components/ListFilterButtons/ToggleListMenu.jsx
Labels: 🐞 BugFix

#269 Style 버튼, 채팅 리스트, 검색 목록 화면 스타일 추가
  src/components/Button/Button.module.css
  src/components/ChatProfileCard/ChatProfileCard.module.css
  src/components/ListSearch/ListSearch.module.css
Labels: 🚧 Refactor

#271 Bugfix 회원가입 토스트 폴백 충돌 개선
  src/pages/Register/Register.jsx
Labels: 🐞 BugFix
