Repository FRONTENDSCHOOL10/we-are-final-family, pull requests merged in 2024-08, with the labels that each got.

#3 📑 Docs : PR 템플릿 생성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📑 Docs

#6 Feat:Button 컴포넌트 제작
  src/components/Button/Button.jsx
  src/components/Button/Button.module.css
  src/components/Button/ButtonWrap.jsx
Labels: 🌟 Feature

#8 Feature 컴포넌트 네비게이션 마크업 스타일링 기능구현 #4
  src/assets/button/icon/board.svg
  src/assets/button/icon/chat.svg
  src/assets/button/icon/onboard.svg
  src/assets/button/icon/onchat.svg
  src/assets/button/icon/onprofile.svg
  src/assets/button/icon/onship.svg
  src/assets/button/icon/profile.svg
  src/assets/button/icon/ship.svg
  src/components/navigation/Navigation.jsx
  src/components/navigation/Navigation.module.css
Labels: 🌟 Feature

#11 Feat/interest component/g
  src/assets/button/icon/Group 3.svg
  src/assets/button/icon/check.svg
  src/components/InterestCard/InterestCard.jsx
  src/components/InterestCard/InterestCard.module.css
  src/components/InterestCardButton/InterestCardButton.jsx
  src/components/InterestCardButton/InterestCardButton.module.css
Labels: 🌟 Feature

#12 Feature 컴포넌트 카테고리 셀렉트 마크업 스타일링 기능구현 #9
  src/assets/button/arrow/down.svg
  src/assets/button/arrow/left.svg
  src/components/CategorySelect/CategorySelect.jsx
  src/components/CategorySelect/CategorySelect.module.css
Labels: 🌟 Feature

#14 Feat/fix button/g
  src/assets/button/icon/plus.svg
  src/components/Button/Button.jsx
  src/components/Button/Button.module.css
  src/components/Button/ButtonWrap.jsx
  src/components/InterestCardButton/InterestCardButton.module.css
Labels: 🚧 Refactor

#16 Feat:Toggle component 구현
  src/components/Toggle/Toggle.jsx
  src/components/Toggle/Toggle.module.css
  src/components/ToggleWrapper/ToggleWrapper.jsx
Labels: 🌟 Feature

#18 Style : iconfonts 생성 및 base-font 추가
  src/assets/fonts/icomoon.eot
  src/assets/fonts/icomoon.svg
  src/assets/fonts/icomoon.ttf
  src/assets/fonts/icomoon.woff
  src/styles/iconfonts.css
  src/styles/variables.css
Labels: 🌟 Feature

#21 BugFix : iconfonts 관련 수정
  App.jsx
  src/components/ExampleForIconFonts/Exam.jsx
  src/components/ExampleForIconFonts/Exam.module.css
  src/styles/iconfonts.css
  src/styles/variables.css
Labels: 🚧 Refactor

#22 Feat/compoent date selector/l #19
  src/assets/button/icon/calendar.svg
  src/components/DateSelector/Calender/Calender.jsx
  src/components/DateSelector/Calender/Calender.module.css
  src/components/DateSelector/DateSelector.jsx
  src/components/DateSelector/DateSelector.module.css
  src/styles/media.css
Labels: 🌟 Feature

#24 Refator 네비게이션 리팩토링
  index.html
  public/logo.svg
  public/vite.svg
  src/components/navigation/Data/navigationData.js
  src/components/navigation/Navigation.jsx
Labels: 🚧 Refactor

#28 Feat: 프로필 테스트 이미지 추가 및 프로필 이미지 컴포넌트
  src/assets/testImg/bonobobono.jpeg
  src/components/ProfileImg/Profile.module.css
  src/components/ProfileImg/ProfileImg.jsx
Labels: 🌟 Feature

#30 Refactor 아이콘 폰트 보완 및 타이포그래피 추가
  src/assets/fonts/icomoon.eot
  src/assets/fonts/icomoon.svg
  src/assets/fonts/icomoon.ttf
  src/assets/fonts/icomoon.woff
  src/components/ExampleForIconFonts/Exam.jsx
  src/components/ExampleForIconFonts/Exam.module.css
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
  src/styles/iconfonts.css
  src/styles/variables.css
Labels: 🚧 Refactor

#31 Refator 데이터 셀럭터 리팩토링
  src/components/DateSelector/Calender/Calender.jsx
  src/components/DateSelector/Calender/Calender.module.css
  src/components/DateSelector/DateSelector.jsx
Labels: 🚧 Refactor

#33 Feature 헤더 마크업 및 스타일링
  src/assets/fonts/icomoon.eot
  src/assets/fonts/icomoon.svg
  src/assets/fonts/icomoon.ttf
  src/assets/fonts/icomoon.woff
  src/components/Header/Header.jsx
  src/components/Header/HeaderBoard.jsx
  src/components/Header/HeaderBoard.module.css
  src/components/Header/HeaderChatDetail.jsx
  src/components/Header/HeaderChatDetail.module.css
  src/components/Header/HeaderDetail.jsx
  src/components/Header/HeaderDetail.module.css
  src/components/Header/HeaderHome.jsx
  src/components/Header/HeaderHome.module.css
  src/components/Header/HeaderSearch.jsx
  src/components/Header/HeaderSearch.module.css
  src/components/Header/HeaderTitle.jsx
  src/components/Header/HeaderTitle.module.css
  src/components/Header/HeaderWrite.jsx
  src/components/Header/HeaderWrite.module.css
  src/components/IconButton/IconButton.jsx
  src/components/IconButton/IconButton.module.css
  src/styles/iconfonts.css
Labels: 🌟 Feature

#34 Refator 컴포넌트 아이콘폰트 적용
  src/components/CategorySelect/CategorySelect.jsx
  src/components/CategorySelect/CategorySelect.module.css
  src/components/DateSelector/Calender/Calender.jsx
  src/components/DateSelector/DateSelector.jsx
  src/components/DateSelector/DateSelector.module.css
  src/components/navigation/Data/navigationData.js
  src/components/navigation/Navigation.jsx
  src/components/navigation/Navigation.module.css
Labels: 🚧 Refactor

#36 Feature 컴포넌트 인원 카운터 마크업 스타일링 기능구현
  src/components/PersonnelCounter/PersonnelCounter.jsx
  src/components/PersonnelCounter/PersonnelCounter.module.css
  src/styles/reset.css
Labels: 🌟 Feature
